### ISSUE TITLE
TypeError: Unable to cast object of type 'NiL.JS.Core.JSValue' to type 'NiL.JS.Core.JSObject'.

### ISSUE THREAD

**Issue by matteofabbri** [nilproject/NiL.JS#185] opened 2019-09-25 10:08 UTC
Using latest Core nuget on this file : https://github.com/cazala/synaptic/blob/master/dist/synaptic.js

I got this exception:
TypeError: Unable to cast object of type 'NiL.JS.Core.JSValue' to type 'NiL.JS.Core.JSObject'.

With empty js code line or info about what part of the code caused the error.
I would be happy to trying to fix it by myself but i dont understand how to build the core solution :( 

Stacktrace:
   at NiL.JS.ExceptionHelper.Throw(Error error, Exception innerException)
   at NiL.JS.Core.Functions.MethodProxy.invokeMethod(JSValue targetValue, Expression[] argumentsSource, Arguments argumentsObject, Context initiator)
   at NiL.JS.Core.Functions.MethodProxy.InternalInvoke(JSValue targetValue, Expression[] argumentsSource, Context initiator, Boolean withSpread, Boolean withNew)
   at NiL.JS.Expressions.Call.Evaluate(Context context)
   at NiL.JS.Statements.CodeBlock.evaluateLines(Context context, Int32 i, Boolean clearSuspendData)
   at NiL.JS.Statements.CodeBlock.Evaluate(Context context)
   at NiL.JS.BaseLibrary.Function.evaluateBody(Context internalContext)
   at NiL.JS.Core.Functions.SimpleFunction.fastInvoke(JSValue targetObject, Expression[] arguments, Context initiator)
   at NiL.JS.Expressions.Call.Evaluate(Context context)
   at NiL.JS.Statements.Return.Evaluate(Context context)
   at NiL.JS.Statements.CodeBlock.evaluateLines(Context context, Int32 i, Boolean clearSuspendData)
   at NiL.JS.Statements.CodeBlock.Evaluate(Context context)
   at NiL.JS.BaseLibrary.Function.evaluateBody(Context internalContext)
   at NiL.JS.Core.Functions.SimpleFunction.fastInvoke(JSValue targetObject, Expression[] arguments, Context initiator)
   at NiL.JS.Expressions.Call.Evaluate(Context context)
   at NiL.JS.Statements.Return.Evaluate(Context context)
   at NiL.JS.Statements.CodeBlock.evaluateLines(Context context, Int32 i, Boolean clearSuspendData)
   at NiL.JS.Statements.CodeBlock.Evaluate(Context context)
   at NiL.JS.BaseLibrary.Function.evaluateBody(Context internalContext)
   at NiL.JS.Core.Functions.SimpleFunction.fastInvoke(JSValue targetObject, Expression[] arguments, Context initiator)
   at NiL.JS.Expressions.Call.Evaluate(Context context)
   at NiL.JS.Expressions.SetProperty.Evaluate(Context context)
   at NiL.JS.Statements.IfElse.Evaluate(Context context)
   at NiL.JS.Statements.IfElse.Evaluate(Context context)
   at NiL.JS.Statements.IfElse.Evaluate(Context context)
   at NiL.JS.Statements.CodeBlock.evaluateLines(Context context, Int32 i, Boolean clearSuspendData)
   at NiL.JS.Statements.CodeBlock.Evaluate(Context context)
   at NiL.JS.BaseLibrary.Function.evaluateBody(Context internalContext)
   at NiL.JS.Core.Functions.SimpleFunction.fastInvoke(JSValue targetObject, Expression[] arguments, Context initiator)
   at NiL.JS.Expressions.Call.Evaluate(Context context)
   at NiL.JS.Statements.CodeBlock.evaluateLines(Context context, Int32 i, Boolean clearSuspendData)
   at NiL.JS.Statements.CodeBlock.Evaluate(Context context)
   at NiL.JS.Script.Evaluate(Context context)
   at NiL.JS.Module.Run()
   at Maddelena.Script.Runner.Script.ScriptService.Run(Module module)

**Comment by nilproject** [comment] 2019-09-25 13:21
Thanks for this bug report.
But this is duplicate of #184

**Closed as completed** 2019-10-07 09:32 UTC
Labels: duplicate
